# Notebook 01 — Structural Cleaning (Suveillance Dataset)
This notebook performs the initial data profiling: **Structural Cleaning**.

Here, we load the raw surveillance data and identify:
1. Column names to be standardized
2. Inconsistent data types
3. Structural duplicates
4. Date-like columns to be converted

This step ensures the dataset is fit for further cleaning (categorical, numerical)

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
df = pd.read_csv('../data/raw/outbreak_surveillance_data.csv')
clean_df = df
df.head()

   Patient_Id Collection Date       Location     pathogen  Age  Severity score
0         202      2026-01-29     South East        Flu A   34             3.0
1         279      2026-01-07     South East  Influenza A   69             2.0
2         192      2026-01-05  North Central      Unknown   82             1.0
3         114      2026-01-22     North West        Flu A   29             5.0
4         206      2026-01-29     North West  Influenza A   70             5.0

## Initial Dataset Overview
Before making any changes, we review:

1. Dataset shape
2. Column names
3. Data types
4. Number of missing values
5. A quick visual feel

In [22]:
print('Dataset Shape:', clean_df.shape)
print('\nColumn Names:', clean_df.columns.tolist())
print('\nData Types:\n', clean_df.dtypes)
print('\nMissing Values:\n', clean_df.isna().sum())

Dataset Shape: (500, 6)

Column Names: ['Patient_Id', 'Collection Date', 'Location', 'pathogen', 'Age', 'Severity score']

Data Types:
 Patient_Id           int64
Collection Date     object
Location            object
pathogen            object
Age                  int64
Severity score     float64
dtype: object

Missing Values:
 Patient_Id           0
Collection Date      0
Location             0
pathogen             0
Age                  0
Severity score     145
dtype: int64

### Column Names Standardization

In [23]:
clean_df.columns = (
    clean_df.columns.astype(str)
    .str.lower()
    .str.strip()
    .str.replace(r'[ -]+', '_', regex = True)
)
clean_df.head()

   patient_id collection_date       location     pathogen  age  severity_score
0         202      2026-01-29     South East        Flu A   34             3.0
1         279      2026-01-07     South East  Influenza A   69             2.0
2         192      2026-01-05  North Central      Unknown   82             1.0
3         114      2026-01-22     North West        Flu A   29             5.0
4         206      2026-01-29     North West  Influenza A   70             5.0

### Data Types Fixing

**Date-like column**

In [24]:
clean_df['collection_date'] = pd.to_datetime(clean_df['collection_date'], errors = 'coerce')

**Categorical Columns**

In [25]:
cat_col = [
    'location',
    'pathogen'
]

for col in cat_col:
    df[col] = df[col].astype('category')

### Checking and Removing Duplicate Records

In [26]:
before = clean_df.shape[0]
clean_df = clean_df.drop_duplicates()
after = clean_df.shape[0]

print(f'Removed {before - after} duplicate rows.')

Removed 0 duplicate rows.

### Structural Integrity Check

In [27]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   patient_id       500 non-null    int64
 1   collection_date  500 non-null    datetime64[ns]
 2   location         500 non-null    category
 3   pathogen         500 non-null    category
 4   age              500 non-null    int64
 5   severity_score   355 non-null    float64
dtypes: category(2), datetime64[ns](1), float64(1), int64(2)
memory usage: 17.1 KB

# Save Structurally Cleaned Dataset
We save this version into the data/interim folder for use in Notebook 02.

In [28]:
clean_df.to_csv('../data/interim/structural_cleaned_data.csv', index = False)